import { Metadata, Viewport } from "next";

export const metadata: Metadata = {
  manifest: "/manifest.json",
  title: "Next.js",
  description: "Generated by Next.js",
};
export const viewport: Viewport = {
  themeColor: "#FFFFFF",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
